services:
  web:
    build:
      context: .
      dockerfile: Todozra.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: todozra-web
    ports:
      - "8080:8080"
    volumes:
      - todozra-data:/app
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080

volumes:
  todozra-data:
